EvoPC.WEB/Models/ErrorViewModel.cs
using System;

namespace EvoPC.WEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EvoPC.WEB/Controllers/HomeController.cs
using EvoPC.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using EvoPC.WEB;
using System.Collections.Generic;

namespace EvoPC.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProcesorServices procesorService;

        public HomeController(IProcesorServices procesorService)
        {
            this.procesorService = procesorService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var procesor = procesorService.GetAllProcesors();
            return View(procesor);
        }

        [HttpGet]
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {
            var procesor = procesorService.GetProcesor(id);
            return View(procesor);
        }

        [HttpPost]
        [Route("Add/{id}")]

        public IActionResult Add(int id)
        {
            var shopList = HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);

            if (shopList == null)
                shopList = new List<int>();

            if (!shopList.Contains(id))
                shopList.Add(id);

            HttpContext.Session.Set(SessionHelper.ShoppingCart, shopList);

            return RedirectToAction("Index", "Home", procesorService.GetAllProcesors());
        }

        [HttpPost]
        [Route("Remove/{id}")]

        public IActionResult Remove(int id)
        {
            var shopList = HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);

            if (shopList == null)
                return RedirectToAction("Index", "Home", procesorService.GetAllProcesors());

            if (shopList.Contains(id))
                shopList.Remove(id);

            HttpContext.Session.Set(SessionHelper.ShoppingCart, shopList);

            return RedirectToAction("Index", "Home", procesorService.GetAllProcesors());
        }

    }
}

EvoPC.WEB/Controllers/ProcesorController.cs
using EvoPC.Models.DTOs.VM;
using EvoPC.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoPC.WEB.Controllers
{
    [Route("[Controller]")]
    public class ProcesorController : Controller
    {
        private readonly IProcesorServices service;

        public ProcesorController(IProcesorServices service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllProcesors();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new ProcesorVM();
            dto.SocketTypes = service.GetSocketTypes();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(ProcesorVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Exista o eroare");
                dto.SocketTypes = service.GetSocketTypes();
                return View(dto);
            }

            service.AddProcesor(dto);
            return View("Index", service.GetAllProcesors());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetProcesor(id);
            dto.SocketTypes = service.GetSocketTypes();
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, ProcesorVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Exista o eroare!");
                dto.SocketTypes = service.GetSocketTypes();
                return View(dto);
            }

            service.UpdateProcesor(id, dto);
            return View("Index", service.GetAllProcesors());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteProcesor(id);
            return Json(new { succes = true, message = "Stergere cu succes!" });
        }
    }
}

EvoPC.WEB/Controllers/SocketTypeController.cs
using EvoPC.Models.DTOs.VM;
using EvoPC.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EvoPC.WEB.Controllers
{
    [Route("[Controller]")]
    public class SocketTypeController : Controller
    {
        private readonly ISocketTypeService service;

        public SocketTypeController(ISocketTypeService service)
        {
            this.service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var list = service.GetAllSocketType();
            return View(list);
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            var dto = new SocketTypeVM();
            return View(dto);
        }

        [HttpPost]
        [Route("New")]
        public IActionResult New(SocketTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Exista o eroare");
                return View(dto);
            }

            service.AddSocketType(dto);
            return View("Index", service.GetAllSocketType());
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id)
        {
            var dto = service.GetSocketType(id);
            return View(dto);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult Edit(int id, SocketTypeVM dto)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Exista o eroare!");
                return View(dto);
            }

            service.UpdateSocketType(id, dto);
            return View("Index", service.GetAllSocketType());
        }

        [HttpDelete]
        [Route("Delete/{id}")]
        public JsonResult Delete(int id)
        {
            service.DeleteSocketType(id);
            return Json(new { succes = true, message = "Stergere cu succes!" });
        }
    }
}

EvoPC.WEB/Views/Home/Details.cshtml
@model ProcesorVM

@inject IHttpContextAccessor HttpContextAccessor
@{
    bool isInBag = false;
    var lstCart = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    if (lstCart != null && lstCart.Contains(Model.Id))
        isInBag = true;

    var route = isInBag ? "/Remove/{0}" : "/Add/{0}";
    route = string.Format(route, Model.Id);
}
<html>
<body style="background-color: #ffdb99; ">

    <h2 class="text-info text-dark" style="color:black;">Detalii Procesor</h2>

    <form action="@route" method="post">

        <div class="p-4 border rounded row border-dark" style="background-color: #420303;">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-4 text-white" style="font-size:20px;">
                        <label>Denumire Procesor</label>
                    </div>
                    <div class="col-4">
                        <input asp-for="Name" readonly class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4 text-white" style="font-size:20px;">
                        <label>Pret</label>
                    </div>
                    <div class="col-4">
                        <input asp-for="Pret" readonly class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4 text-white"style="font-size:20px;">
                        <label>Descriere</label>
                    </div>
                    <div class="col-4" >
                        @Html.TextArea("Description", Model.Description, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4"></div>
                    <div class="col-8">
                        @if (isInBag)
                        {
                            <button type="submit" value="Stergeti din cos" class="btn btn-danger form-control">Stergeti din cos</button>
                        }
                        else
                        {
                            <button type="submit" value="Adaugati in cos" class="btn btn-primary form-control">Adaugati in cos</button>
                        }
                    </div>
                </div>

            </div>

            <div class="col-1">


            </div>

            <div class="col-3">

                <img src="~/@Model.ImagePath" alt="no image" width="100%" style="border-radius:5px; border:1px solid #bbb9b9;" />
            </div>
        </div>

        <br />

        <div class="form-group">
            <a asp-action="Index" class="btn btn-success">Inapoi la lista</a>
        </div>

    </form>
</body>
</html>

EvoPC.WEB/Views/Home/Index.cshtml
@model IEnumerable<ProcesorVM>;

@{
    ViewData["Title"] = "Home Page";
    var detailsRoute = "/Details/{0}";
}
<html>
<body style="background-color: #ffdb99; ">
    @*#ffdb99*@

    <div class="row">

        @foreach (var procesor in Model)
        {
            <div class="col-4">
                <div class="card mb-4" style="background-image: linear-gradient(rgb(66,66,66),rgb(66,66,66),#FFFFFF); ">

                    <div class="card-header" style="color:black;">
                        <h4 class="my-0 font-weight-normal">
                            <label style="font-size:25px;color: white;">@procesor.Name</label>
                        </h4>
                    </div>

                    <img class="card-img-top" style="height:100%" src="~/@procesor.ImagePath" alt="no image" />

                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <label style="font-size:20px; color:black"><b>$@procesor.Pret</b></label>
                            </div>
                            <a href="@string.Format(detailsRoute,procesor.Id)" class="btn fa-pull-right btn-outline-info font-weight-bold" style="color:black">Detalii</a>
                        </div>
                    </div>

                </div>
            </div>
        }

    </div>
</body>
</html>

EvoPC.WEB/Views/Procesor/Edit.cshtml
@model ProcesorVM

@{
    ViewData["Title"] = "Editati un procesor";
}

@{ ViewBag.IsNew = false;}

@await Html.PartialAsync(@"../Shared/Components/_Procesor.cshtml")

EvoPC.WEB/Views/Procesor/Index.cshtml
@model IEnumerable<ProcesorVM>;

@{
    ViewData["Title"] = "Procesoare";
}
<html>
<body style="background-color: #ffdb99; ">
    <div class="row mb-2 mt-2 operationsButtons">
        <div class="col-md-12">
            <a href="/Procesor/New" class="btn btn-new btn-outline-new font-weight-bold mr-2" data-toggle="tooltip" title="New" data-placement="top">
                <span class="fa fa-plus-circle"></span>
            </a>

            <button class="btn btn-outline-dark font-weight-bold mr-2" data-toggle="tooltip" title="Edit" data-placement="top" onclick="Procesor.onEditBtnPress()">
                <span class="fa fa-edit"></span>
            </button>

            <button type="button" class="btn btn-delete btn-outline-delete font-weight-bold mr-2" id="btnDelete" data-toggle="tooltip" data-placement="top" title="Delete" onclick="Procesor.onDelete()">
                <span class="fa fa-trash"></span>
            </button>
        </div>
    </div>

    <br /><br />

    <table id="table" class="table table-hover table-striped table-dark">
        <thead>
            <tr>
                <th hidden>Procesor Id</th>
                <th>Image</th>
                <th>Procesor name</th>
                <th>Price</th>
                <th>Is in stoc</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr id="@item.Id">
                    <td hidden>@item.Id</td>
                    <td><img style="width: 300px; height: 150px;" src="~/@item.ImagePath" alt="Nu exista imagine momentan" /></td>
                    <td>@item.Name</td>
                    <td>@item.Pret</td>
                    <td><input type="checkbox" checked="@item.EsteInStoc" /></td>
                </tr>
            }

        </tbody>

    </table>
    </body>
</html>

EvoPC.WEB/Views/Procesor/New.cshtml
@model ProcesorVM

@{
    ViewData["Title"] = "Creati un procesor";
}

@{ ViewBag.IsNew = true;}

@await Html.PartialAsync(@"../Shared/Components/_Procesor.cshtml")

EvoPC.WEB/Views/Shared/Components/_CancelSaveBtn.cshtml
<div class="col-sm-12 text-center">
    <br />
    <a class=" btn btn-danger" style="width: 100px" asp-action="Index"><em class="fas fa-undo-alt"></em> Cancel</a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button type="submit" style="width: 100px" class="btn btn-success"><em class="fas fa-save"></em> Save</button>
</div>

EvoPC.WEB/Views/Shared/Components/_Procesor.cshtml
@model ProcesorVM

@{
    string action = "";
    var isNew = (bool)ViewBag.IsNew;
    if(isNew)
        action = "/Procesor/New";
    else
        action = string.Format("/Procesor/Edit/{0}", Model.Id);
}

<html>
<body style="background-color: #ffdb99; ">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 table-round shadow" style="background-color: #420303">

            <br />
            <div style="color:white;">
                <h4>Procesor</h4>
            </div>
            <br />

            <div class="col-xl-12">
                <input asp-for="Id" hidden />

                <form action="@action" method="post" enctype="multipart/form-data">

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <br />
                    <div class="row">

                        <div class="col-sm-12 col-lg-12">

                            <div class="row">

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label "style="color:white;">Denumire procesor</label>
                                </div>

                                <div class="col-xs-12 col-sm-4">
                                    <input asp-for="Name" class="form-control" /><br />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label "style="color:white;">Pret</label>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <input asp-for="Pret" class="form-control" /><br />
                                    <span asp-validation-for="Pret" class="text-danger"></span>
                                </div>

                            </div>

                            <div class="row">

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label "style="color:white;">Este in stoc</label>
                                </div>

                                <div class="col-xs-12 col-sm-4">
                                    <input type="checkbox" asp-for="EsteInStoc" /><br />
                                    <span asp-validation-for="EsteInStoc" class="text-danger"></span>
                                </div>

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label "style="color:white;">Socket</label>
                                </div>

                                <div class="col-xs-12 col-sm-4">
                                    @Html.DropDownList("SocketTypeId", new SelectList(Model.SocketTypes, "Id", "Name", Model.SocketTypeId), new { @class = "form-control" })
                                    <span asp-validation-for="Pret" class="text-danger"></span>
                                </div>
                            </div>

                            <br />
                            <div class="row">
                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label " style="color:white;">Incarcati o imagine </label>
                            </div>

                                <div class="col-xs-12 col-sm-4">
                                    <input id="fileInput" type="file" asp-for="ProcImage" class="custom-file-input" onchange="Procesor.onCHangeFile(event)" /><br />
                                    <label id="fileUploadlabel" class="custom-file-label" for="fileInput">Alegeti un fisier</label>
                                    <span asp-validation-for="ProcImage" class="text-danger"></span>
                                </div>
                            </div>

                            <br />

                            <div class="row">

                                <div class="col-xs-12 col-sm-2">
                                    <label class="control-label "style="color:white;">Descriere</label>
                                </div>

                                <div class="col-xs-12 col-sm-10">
                                    @Html.TextArea("Description", Model.Description, new { @class = "form-control" })
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>

                            </div>

                            <br />

                            @if (!isNew)
                            {
                                <div class="row">

                                    <div class="col-xs-12 col-sm-2">
                                        <label class="control-label ">Procesor image</label>
                                    </div>

                                    <div class="col-xs-12 col-sm-10">
                                        <img style="width: 300px; height:150px;" src="~/@Model.ImagePath" alt="Nu exista imagine pentru acest produs" />
                                    </div>

                                </div>


                            }

                        </div>

                        @await Html.PartialAsync(@"_CancelSaveBtn.cshtml")
                    </div>

                </form>

            </div>
        </div>
    </div>
    </body>
</html>

EvoPC.WEB/Views/Shared/Components/_SocketType.cshtml
@model SocketTypeVM

@{
    string action = "";
    if ((bool)ViewBag.IsNew)
        action = "/SocketType/New";
    else
        action = string.Format("/SocketType/Edit/{0}", Model.Id);

}
<html>
<body style="background-color: #ffdb99; ">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 table-round shadow" style="background-color: #420303">

            <br />
            <div style="color:white;">
                <h4>Socket Type</h4>
            </div>
            <br />

            <div class="col-xl-12">
                <input asp-for="Id" hidden />

                <form action="@action" method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <br />
                    <div class="row">

                        <div class="col-sm-12 col-lg-6">
                            <div class="row">
                                <div class="col-xs-12 col-sm-4">
                                    <label class="control-label" style="color:white; font-size:15px;">Denumire Socket</label>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <input asp-for="Name" class="form-control" /><br />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        @await Html.PartialAsync(@"_CancelSaveBtn.cshtml")
                    </div>

                </form>

            </div>
        </div>
    </div>
    </body>
</html>

EvoPC.WEB/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{
    var shoppingList = HttpContextAccessor.HttpContext.Session.Get<List<int>>(SessionHelper.ShoppingCart);
    var shoppingCount = shoppingList == null ? 0 : shoppingList.Count;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EvoPC</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/site.js"></script>

    <script src="~/js/socketType.js"></script>
    <script src="~/js/Procesor.js"></script>

</head>
<body>
    <header >
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #420303;">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">EvoPC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="SocketType" asp-action="Index">SocketType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Procesor" asp-action="Index">Procesor</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white"><span class="fas fa-shopping-cart"></span> &nbsp; (@shoppingCount)</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EvoPC.WEB -
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EvoPC.WEB/Views/SocketType/Edit.cshtml
@model SocketTypeVM

@{
    ViewData["Title"] = "Editati un tip de socket";
}

@{ ViewBag.IsNew = false;}

@await Html.PartialAsync(@"../Shared/Components/_SocketType.cshtml")

EvoPC.WEB/Views/SocketType/Index.cshtml
@model IEnumerable<SocketTypeVM>;

@{
    ViewData["Title"] = "Socket Type";
}

<html>
<body style="background-color: #ffdb99; ">

    <div class="row mb-2 mt-2 operationsButtons" >
        <div class="col-md-12" >
            <a href="/SocketType/New" class="btn btn-new btn-outline-new font-weight-bold mr-2" data-toggle="tooltip" title="New" data-placement="top">
                <span class="fa fa-plus-circle"></span>
            </a>

            <button class="btn btn-outline-dark font-weight-bold mr-2" data-toggle="tooltip" title="Edit" data-placement="top" onclick="SocketType.onEditBtnPress()">
                <span class="fa fa-edit"></span>
            </button>

            <button type="button" class="btn btn-delete btn-outline-delete font-weight-bold mr-2" id="btnDelete" data-toggle="tooltip" data-placement="top" title="Delete" onclick="SocketType.onDelete()">
                <span class="fa fa-trash"></span>
            </button>
        </div>
    </div>

    <table id="table" class="table table-hover table-striped table-dark">
        <thead>
            <tr>
                <th hidden>Socket Type Id</th>
                <th>Socket Type name</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr id="@item.Id">
                    <td hidden>@item.Id</td>
                    <td>@item.Name</td>
                </tr>
            }

        </tbody>

    </table>
</body>
</html>

EvoPC.WEB/Views/SocketType/New.cshtml
@model SocketTypeVM

@{ 
    ViewData["Title"] = "Creati un tip de socket";
}

@{ ViewBag.IsNew = true;}

@await Html.PartialAsync(@"../Shared/Components/_SocketType.cshtml")